export const QUEUE_NAMES = {
  BOOKING: 'bookingQueue',
  TRACKING: 'trackingQueue',
  DLQ: 'deadLetterQueue',
};

export const QUEUE_PROVIDERS = {
  BOOKING_QUEUE: 'BOOKING_QUEUE',
  TRACKING_QUEUE: 'TRACKING_QUEUE',
  DLQ_QUEUE: 'DLQ_QUEUE',
  BOOKING_WORKER: 'BOOKING_WORKER',
  TRACKING_WORKER: 'TRACKING_WORKER',
};
